default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: felipe
  password: "123456"
  host: localhost

development:
  <<: *default
  database: rails_eml_processor_development

test:
  <<: *default
  database: rails_eml_processor_test

production:
  <<: *default
  database: rails_eml_processor_production