default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "postgres" %>
  host: <%= ENV["DATABASE_HOST"] || "db" %>

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] || "rails_eml_processor_development" %>

test:
  <<: *default
  database: rails_eml_processor_test

production:
  <<: *default
  database: rails_eml_processor_production
